chain: ethereum
database:
  type: sqlite
  path: ./final-test.db

contracts:
  - address: "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984"
    name: "UNI Token"
    events:
      - Transfer
      - Approval
    from_block: 19000000

  - address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    name: "USDC"
    events:
      - Transfer
    from_block: 19000000

providers:
  - url: "https://eth-mainnet.g.alchemy.com/v2/q7JZvM10cGQx4KktpMxczFG3lMwOBoXb"
    priority: 1

options:
  batch_size: 10
  confirmations: 0
